1-9-0

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -98,7 +98,7 @@ if test -f $CAMLIMAGESDIR/ci_ps.cma || $HAVE_CDK; then
 		        CAMLIMAGESLIBS="camlimages"
 	        else
 			CAMLIMAGESCONFIGINCLUDE="include $CAMLIMAGESDIR/Makefile.config"
-	                CAMLIMAGESLIBS='$(WITH_CAMLIMAGES:.cma=)'
+	                CAMLIMAGESLIBS='$(WITH_CAMLIMAGES:.cma=) $(WITH_LABLGTKIMAGE:.cma=)'
 	        fi
 	else
 		AC_MSG_RESULT(found, but bit too old)
@@ -121,28 +121,83 @@ else
 	exit 1
 fi
 
-dnl CamlTk
+dnl lablgtk library
 
-CAMLTKDIR=$CAMLDIR/labltk
+LABLGTKDIR_MESSAGE="Not found"
+HAVE_LABLGTK="false"
 
-AC_MSG_CHECKING(for camltk+)
-AC_ARG_WITH(camltk, [  --with-camltk+=dir      specify camltk+ library directory],
+dnl used for Makefile.build
+LABLGTTKIMGDIR=""
+
+AC_MSG_CHECKING(checking lablgtk)
+
+if test "$NOEXTERNAL" = "true"; then
+  AC_MSG_RESULT(disabled)
+else
+  if test -d "$CAMLDIR/lablgtk"; then
+    LABLGTKDIR="$CAMLDIR/lablgtk"
+    LABLGTKLIBS=lablgtk	
+  fi
+  
+  AC_ARG_WITH(lablgtk, [  --with-lablgtk=dir      specify lablgtk library directory],
+    if test "$withval" != "no" ; then  
+  	  if test -f $withval/gtk.ml; then
+  	    LABLGTKDIR="$withval"
+  	  else
+  	    LABLGTKDIR=""
+  	    echo "**************** ERROR ******************"
+  	    echo "gtk.ml is not found in the directory \"$withval\", which you specified with --with-lablgtk option."
+  	    echo "*****************************************"
+  	  fi
+    fi)
+  
+  if test "X$LABLGTKDIR" = "X"; then
+    LABLGTKDIR_MESSAGE="Not found"
+    AC_MSG_RESULT($LABLGTKDIR_MESSAGE)
+    HAVE_LABLGTK="false"
+  else
+    LABLGTKDIR_MESSAGE="found at $LABLGTKDIR"
+    AC_MSG_RESULT($LABLGTKDIR_MESSAGE)
+    AC_MSG_CHECKING(the version of lablgtk)
+    grep image: $LABLGTKDIR/gdk.mli > /dev/null
+    GDK_MLI_NEW=$?
+    if test -f $LABLGTKDIR/gBin.mli -a "$GDK_MLI_NEW" = "1"; then
+      HAVE_LABLGTK="true"
+      LABLGTKIMGDIR="lablgtk"
+      AC_MSG_RESULT(ok)
+    else
+      LABLGTKDIR=""
+      HAVE_LABLGTK="false"
+      LABLGTKDIR_MESSAGE="found, but too old"
+      echo "**************** ERROR ******************"
+      echo "Your lablgtk seems to be old. Install CVS version."
+      echo "*****************************************"
+    fi 
+  fi
+fi
+
+dnl LablTk
+
+LABLTKDIR=$CAMLDIR/labltk
+
+AC_MSG_CHECKING(for labltk)
+AC_ARG_WITH(labltk, [  --with-labltk=dir      specify labltk library directory],
   if test "$withval" != "no" ; then  
-	CAMLTKDIR=$withval
+	LABLTKDIR=$withval
   else
 	AC_MSG_RESULT(no)
-	CAMLTKDIR=nope
+	LABLTKDIR=nope
   fi)
 
-if test -f $CAMLTKDIR/cTk.cmi || $HAVE_CDK; then
+if test -f $LABLTKDIR/cTk.cmi || $HAVE_CDK; then
 	AC_MSG_RESULT(found)
-	HAVE_CAMLTK="true"
-	CAMLTKLIB=$CAMLTKDIR/labltk.cma
+	HAVE_LABLTK="true"
+	LABLTKLIB=$LABLTKDIR/labltk.cma
 else
 	AC_MSG_RESULT(no)
-	HAVE_CAMLTK="false"
+	HAVE_LABLTK="false"
 	echo "***************** Warning *******************"
-	echo "Your camltk library is too old. Use the latest one,"
+	echo "Your labltk library is too old. Use the latest one,"
 	echo "found in the O'Caml CVS tree"
 	echo "*******************************************"
 fi
@@ -205,14 +260,17 @@ AC_SUBST(CAMLIMAGESDIR)
 AC_SUBST(CAMLIMAGESCONFIGINCLUDE)
 AC_SUBST(HAVE_CAMLIMAGES)
 AC_SUBST(CAMLIMAGESLIBS)
+AC_SUBST(LABLGTKDIR)
+AC_SUBST(HAVE_LABLGTK)
+AC_SUBST(LABLGTKLIBS)
 AC_SUBST(HAVE_GS)
 AC_SUBST(PATH_GS)
 AC_SUBST(TEXMFMAIN)
 AC_SUBST(PATH_KPSEWHICH)
 AC_SUBST(PATH_GZIP)
-AC_SUBST(HAVE_CAMLTK)
-AC_SUBST(CAMLTKDIR)
-AC_SUBST(CAMLTKLIB)
+AC_SUBST(HAVE_LABLTK)
+AC_SUBST(LABLTKDIR)
+AC_SUBST(LABLTKLIB)
 AC_SUBST(INSTALLTARGET)
 
 dnl BUILD OUR OWN LIBDIR
@@ -234,7 +292,8 @@ echo "------------------------------------------------- Configuration finished"
 echo "Language:    $CAML version $CAMLVERSION"
 echo "cdk_config:  $HAVE_CDK"
 echo "Camlimages:  $HAVE_CAMLIMAGES"
-echo "CamlTk:      $HAVE_CAMLTK"
+echo "LablTk:      $HAVE_LABLTK"
+echo "LablGtk:     $HAVE_LABLGTK"	
 echo "GS:          $GS_UPTO_DATE version $GS_VERSION at $PATH_GS"
 echo "Resources:   $ADVI_LOC/"
 echo "------------------------------------------------------------------------"
